//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingSiteBuilder.ReadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendee()
        {
            CreateDate = DateTime.Now;
            LastUpdated = DateTime.Now;
        }
    
        public long AttendeeID { get; set; }
        public long PersonID { get; set; }
        public long WeddingID { get; set; }
        public string WeddingRole { get; set; }
        public string Relationship { get; set; }
        public string Side { get; set; }
        public Nullable<bool> Attending { get; set; }
        public Nullable<bool> PartyMember { get; set; }
        public string PartyMemberBlurb { get; set; }
        public Nullable<bool> RSVPStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> NumberofRSVPs { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
