//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingSiteBuilder.ReadModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeddingSiteBuilderEntities : DbContext
    {
        public WeddingSiteBuilderEntities()
            : base("name=WeddingSiteBuilderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendee> Attendees { get; set; }
        public virtual DbSet<Ceremony> Ceremonies { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Reception> Receptions { get; set; }
        public virtual DbSet<Registry> Registries { get; set; }
        public virtual DbSet<RSVPLink> RSVPLinks { get; set; }
        public virtual DbSet<Wedding> Weddings { get; set; }
    }
}
